### PR TITLE
Improve Italian translation

### PR DESCRIPTION
**Pull request by Jiack214**

### CODE REVIEW

**Comment by Fs00** [comment]
Please merge this @BijoySingh! Current italian translation sucks :/

**Comment by BijoySingh** [comment]
@Jiack214, this is a massively old pull request, and I apologize for not looking at it sooner. Do you mind if I directly move these changes into master instead of merging this, which will be a lot of pain? 

The reason I am asking is, it kinda takes away the attribution from your revision, which I don't intend to do unless it's cool with you :)

**Comment by Jiack214** [comment]
Yeah, no problem. Do whatever you want with my changes :)

Btw sorry but I have no time these days to create an updated PR.

**Comment by Fs00** [comment]
@BijoySingh This can be closed since #145 incorporates these changes.

**Pull request closed without merging**
